:current-module: amp-yospace
include::ROOT:partial$amp-gobal-attributes.adoc[]
:imagesdir: image-catalog
:amp-plugin-docs: https://developer.yospace.com/sdk-documentation/apple/userguide/latest/en/index-en.html
:amp-plugin-sample-ios: https://mdtp-a.akamaihd.net/amp-ios-sdk/samples/AmpYoSpaceSample.zip
:amp-plugin-sample-tvos: https://mdtp-a.akamaihd.net/amp-ios-sdk/samples/AmpYoSpaceSampleTV.zip
:plugin-common-name:YoSpace

= YoSpace Analytics

The AmpYoSpace plugin offers a quick way to integrate AmpPlayer with {amp-plugin-docs}[YoSpace SDK]. This plugin enables the reporting of data collected by {plugin-common-name} in your application, efectively tracking your video activity.

You can check out our basic implementation, please refer to our application samples:

* {amp-plugin-sample-ios}[AMP {plugin-common-name} application sample for iOS].
* {amp-plugin-sample-tvos}[AMP {plugin-common-name} application sample for tvOS].

:framework-name: AmpYoSpace
:external-sdk-name: YoSpace Analytics
:external-sdk-url: https://yospacerepo.jfrog.io/ui/native/apple-sdk-release/com/yospace/admanagement-sdk/
:latest-ios-version: 3.7.3
include::ROOT:partial$amp-instalation.adoc[]

NOTE: To add YoSpace as a pod using Cocoapods. Please refer to https://developer.yospace.com/sdk-documentation/apple/api/yosdk/latest/index.html[their guide].

== Implementation

You need a working implementation of the AmpPlayer before using this plugin. If you need the implementation guide for AmpPlayer please refer to {amp-player-docs}[our documentation].

=== Import

The first step is to import the AmpCore, Amp{plugin-common-name}, and {plugin-common-name} plugins.

[source,swift]
----
import AmpCore
import AmpYoSpace
import YOAdManagement
----

=== Defining the Video Data

After importing the libraries to the file, the next step is to define the properties of the YoSpace session
[source,swift]
----
let properties:YOSessionProperties = YOSessionProperties()
properties.timeout = 2
YOSessionProperties.add(.DEBUG_PARSING)
----

=== Adding a manager

The final step is to add AMP's manager to link the video playback with YoSpace reporting.
[source,swift]
----
manager = AmpYoSpaceManager(url: VIDEO_URL, ampPlayer: AMP_PLAYER_INSTANCE, yoSpaceProperties: properties, playbackMode: .YOVODMode, isLoggingEnabled: true)
----

NOTE: After adding the manager just use the player normally and the reports should be sent to YoSpace.

:date: 7/26/2024
:last-revision: 7/26/2024
include::ROOT:partial$amp-additional-info.adoc[]